name: SFTP Transfer via Gist

on:
  repository_dispatch:
    types: [sftp_transfer]

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log event details
        run: |
          echo "Event received at $(date)"
          echo "Timestamp from request: ${{ github.event.client_payload.timestamp }}"
          echo "Gist ID: ${{ github.event.client_payload.gist_id }}"
      
      - name: Fetch JSON data from Gist
        id: fetch-gist
        run: |
          # Récupérer le contenu du Gist
          echo "Téléchargement des données depuis le Gist..."
          GIST_CONTENT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "User-Agent: GitHub-Action" \
            "https://api.github.com/gists/${{ github.event.client_payload.gist_id }}")
          
          # Extraire l'URL du contenu brut
          RAW_URL=$(echo "$GIST_CONTENT" | grep -o '"raw_url": "[^"]*"' | grep -o 'https://[^"]*')
          
          # Télécharger le contenu JSON brut
          curl -s "$RAW_URL" > septeo.json
          
          # Vérifier que le fichier existe et a un contenu
          if [ -s septeo.json ]; then
            echo "JSON récupéré avec succès ($(stat -c%s septeo.json) octets)"
          else
            echo "Erreur: Impossible de récupérer le contenu JSON"
            exit 1
          fi
          
      - name: Setup SFTP Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ftp.notaires.fr >> ~/.ssh/known_hosts
          echo "SSH directory setup complete"
          
      - name: Transfer File via SFTP
        run: |
          echo "Starting SFTP transfer..."
          sshpass -p "${{ secrets.SFTP_PASSPHRASE }}" sftp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa i00003-septeo@ftp.notaires.fr << EOF
          cd /json
          put septeo.json
          ls -la
          bye
          EOF
          echo "SFTP transfer completed"
          
      - name: Delete Gist after successful transfer
        if: success()
        run: |
          echo "Suppression du Gist temporaire..."
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "User-Agent: GitHub-Action" \
            "https://api.github.com/gists/${{ github.event.client_payload.gist_id }}"
          echo "Gist supprimé"
          
      - name: Cleanup
        if: always()
        run: |
          rm -f septeo.json
          rm -f ~/.ssh/id_rsa
          echo "Cleanup completed"
