name: SFTP Transfer Direct

on:
  repository_dispatch:
    types: [sftp_transfer]

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Log event details
        run: |
          echo "Event received at $(date)"
          echo "Timestamp from request: ${{ github.event.client_payload.timestamp || 'Not provided' }}"
          echo "Debug payload data:"
          echo '${{ toJson(github.event.client_payload) }}'
      
      - name: Create JSON file from payload or create test file
        run: |
          # Vérifier si le payload contient des données json_data
          if [ -n "${{ github.event.client_payload.json_data }}" ]; then
            echo "Création du fichier JSON depuis le payload..."
            echo '${{ toJson(github.event.client_payload.json_data) }}' > septeo.json
          else
            echo "Payload vide ou invalide, création d'un fichier JSON de test..."
            # Créer un JSON de test
            echo '{"test":"Données de test", "date":"'"$(date)"'", "source":"GitHub Actions"}' > septeo.json
          fi
          
          # Vérifier que le fichier a été créé
          if [ -s septeo.json ]; then
            echo "JSON créé avec succès ($(stat -c%s septeo.json) octets)"
            echo "Aperçu du contenu:"
            head -n 5 septeo.json
          else
            echo "ATTENTION: Fichier vide, création d'un nouveau fichier de secours"
            echo '{"backup":"Fichier de secours créé le '"$(date)"'"}' > septeo.json
            echo "Fichier de secours créé"
          fi
          
          # Afficher le contenu du fichier pour déboguer
          echo "Contenu complet du fichier JSON:"
          cat septeo.json
          
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client
          
      - name: Setup SFTP Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ftp.notaires.fr >> ~/.ssh/known_hosts
          echo "Clé privée installée"
          
      - name: Test SSH connection
        run: |
          echo "Test de connexion SSH..."
          sshpass -p "${{ secrets.SFTP_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa i00003-septeo@ftp.notaires.fr 'echo "Connexion réussie" && pwd && ls -la'
        continue-on-error: true
          
      - name: Transfer File via SFTP
        run: |
          echo "Début du transfert SFTP..."
          
          # Premier essai avec sftp
          echo "Tentative SFTP avec chemin absolu..."
          sshpass -p "${{ secrets.SFTP_PASSPHRASE }}" sftp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa i00003-septeo@ftp.notaires.fr << EOF
          pwd
          mkdir -p /json
          cd /json
          pwd
          put septeo.json
          ls -la
          bye
          EOF
        continue-on-error: true
          
      - name: Alternative transfer using scp
        run: |
          echo "Tentative alternative avec SCP..."
          # Créer un nom de fichier unique avec timestamp
          FILENAME="septeo_$(date +%s).json"
          
          # Tenter plusieurs variantes de chemins
          echo "Essai 1: Chemin absolu /json/"
          sshpass -p "${{ secrets.SFTP_PASSPHRASE }}" scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa septeo.json i00003-septeo@ftp.notaires.fr:/json/$FILENAME
          
          echo "Essai 2: Chemin relatif json/"
          sshpass -p "${{ secrets.SFTP_PASSPHRASE }}" scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa septeo.json i00003-septeo@ftp.notaires.fr:json/$FILENAME
          
          echo "Essai 3: À la racine"
          sshpass -p "${{ secrets.SFTP_PASSPHRASE }}" scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa septeo.json i00003-septeo@ftp.notaires.fr:$FILENAME
          
          echo "Transferts SCP terminés"
        continue-on-error: true
          
      - name: Verify file upload
        run: |
          echo "Vérification des fichiers transférés..."
          sshpass -p "${{ secrets.SFTP_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa i00003-septeo@ftp.notaires.fr << EOF
          echo "Contenu du répertoire /json:"
          ls -la /json/
          echo "Contenu du répertoire racine:"
          ls -la
          echo "Contenu du répertoire json (relatif):"
          ls -la json/ 2>/dev/null || echo "Répertoire json/ n'existe pas"
          EOF
          
      - name: Cleanup
        if: always()
        run: |
          rm -f septeo.json
          rm -f ~/.ssh/id_rsa
          echo "Nettoyage terminé"
